baseURL = "https://cathayddt.github.io"
languageCode = "en-us"
title = "Cathay DDT Open Source Software"
theme = "hugograyscale"
[params]
    # Provide some metadata for search and indexing services
    description = ""

[Author]
    name = "cathayddt"
    email = "cathayddt@gmail.com"
